Microverse trial
codecaiine/microverse-trial-review pull request #4
Opened 2022-06-22 16:57 UTC by codecaiine

### Microverse Trial project
- Set up linters
- Styling the page

2022-06-22 17:23 UTC, codecaiine reviewed
Hi @codecaiine , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
* You have the descriptive commits:heavy_check_mark:
* You have the descriptive pull request :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

- [ ] it is a bad practice, Ideally, there should not be any direct commit in master branch. Master branch should contain thoroughly tested and deploy-able version of code which means merge develop branch with master branch whenever you are ready to release your changes. Please create another branch for deployment instead of pushing to the main branch.
- [ ] Use your PR title as an opportunity to set the reviewer up for a review they will want to do. Kindly edit your PR title.

- [ ] Please remove all unnecessary comments and also empty JS file you are not using in your project 
- [ ]  Kindly set up the correct Github actions for linters . Since you are not using javascript in your project, please refer to this [template](https://github.com/microverseinc/linters-config/tree/master/html-css) to set up html-css linters.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-22 17:23 UTC, codecaiine commented on README.md
> +6. **IMPORTANT NOTE**: feel free to research [auto-correct options for Stylelint](https://stylelint.io/user-guide/cli#autofixing-errors) if you get a flood of errors but keep in mind that correcting
- [ ] Please add a descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template), and kindly customize it to your project.

2022-06-22 17:23 UTC, codecaiine commented on js/index.js
> +    *********** */
- [ ] Please remove the index.js file from the project as it does not contain any code and is not used in your project. It s important to remove unused javascript to improve the loading speed and reduce bytes consumed by network activity.

2022-06-22 20:19 UTC, BertrandConxy requested changes
Hi @codecaiine , 

**Good job so far! 👏**

I would like to mention that I liked the way you perform reviews following all the best practices and using GitHub Review features. However, there are some issues that you still need to work on to go to the complete project but you are almost there!

## Highlights
- Use of GitHub review features
- Requesting changes in a polite way
- easy to understand comments

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-22 20:19 UTC, BertrandConxy commented on README.md
> +6. **IMPORTANT NOTE**: feel free to research [auto-correct options for Stylelint](https://stylelint.io/user-guide/cli#autofixing-errors) if you get a flood of errors but keep in mind that correcting
- [ ] It is important to acknowledge how you have recommended the author update his README file as it is in the requirements. Great job 👏. However, **it is also important to tell the author why you request the changes to be made**.
This is to help him know well the reason why he should implement such changes. I would suggest you to add a sentence stating the reason why it is important to make that change. For example, you can tell him that a descriptive README helps the visitors to know all the necessary information about your project so that they can use it or use the codebase as a reference 😺

2022-06-22 20:19 UTC, BertrandConxy commented on js/index.js
> +    *********** */
- [ ] Great explanation here 👍 👏 . In addition to what you have said, I think it would be much better if you also refer to one of the most popular software development principles called **YAGNI**(You'll not gonna need it) and bring up more information to help him learn more. Also, reference some documents like [YAGNI explained](https://www.itexico.com/blog/software-development-kiss-yagni-dry-3-principles-to-simplify-your-life#:~:text=the%20next%20principle.-,YAGNI,remove%20because%20they%20do%20not%20fit%20the%20needs%20of%20the%20product.,-DRY) 😃

2022-06-22 20:25 UTC, BertrandConxy reviewed
[**OPTIONAL**] It is really good to use some emojis 👍  and GIFs in your reviews as they make your reviews more human-friendly 😄

2022-06-23 08:11 UTC, codecaiine commented
Hi @BertrandConxy , 
Thank you for your reviewing and your comments on my project.
I'm implementing it.

2022-06-28 23:17 UTC, merged